version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - run: bundle install && bundle exec jekyll build
  deploy-to-ghpages:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run: bundle install && bundle exec jgd
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            ignore: master
  deploy:
    jobs:
      - deploy-to-ghpages:
          filters:
            branches:
              only: master
